# Site settings
title: Redrum's Blog
email: 88333538@163.com
description: "HTML,CSS"
permalink: /:year/:month/:day/:title.html
baseurl: "http://7pn6ab.com1.z0.glb.clouddn.com"
homeurl: "http://redrum1900.github.io"
url: "redrum1900.github.io"
atom-baseurl: "redrum1900.github.io"
author: "redrum1900"

# Build settings
# permalink: date

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [fenced_code_blocks,no_intra_emphasis,strikethrough,no_intra_emphasis,autolink,tables]

#duoshuo
  comments :
    provider : duoshuo
    duoshuo :
      short_name : redrum

navigations:
  - title: About
    class: fa fa-list-ul
    href: /about/
  - title: Archive
    class: fa fa-tags
    href: /archive/
  - title: Categories
    class: fa fa-user
    href: /categories/
  - title: Tags
    class: fa fa-film
    href: /tags/
  - title: Rss
    class: fa fa-rss
    href: /atom.xml
